// <auto-generated />
using System;
using ChoiceVFileSystemBlazor.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChoiceVFileSystemBlazor.Migrations
{
    [DbContext(typeof(ChoiceVFileSystemBlazorDatabaseContext))]
    [Migration("20240902221311_UpdateSupportfileEntryModelV2")]
    partial class UpdateSupportfileEntryModelV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.DbModels.Ranks.AccountToRanksDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("RankId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AccountToRanksDbModels");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.DbModels.Ranks.RankDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ModifierPower")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SeeLogsPower")
                        .HasColumnType("int");

                    b.Property<int>("ViewPower")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RankDbModels");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Supportfiles.SupportfileDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedByAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("NeededDeletePower")
                        .HasColumnType("int");

                    b.Property<int>("NeededEditPower")
                        .HasColumnType("int");

                    b.Property<int>("NeededSeeLogPower")
                        .HasColumnType("int");

                    b.Property<int>("NeededViewPower")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Supportfiles");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Supportfiles.SupportfileEntryDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedByAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SupportfileId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SupportfileEntryDbModels");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Supportfiles.SupportfileLogsDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModifierAccountId")
                        .HasColumnType("int");

                    b.Property<string>("SupportfileId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SupportfileLogsDbModels");
                });
#pragma warning restore 612, 618
        }
    }
}
