// <auto-generated />
using System;
using ChoiceVFileSystemBlazor.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChoiceVFileSystemBlazor.Migrations
{
    [DbContext(typeof(ChoiceVFileSystemBlazorDatabaseContext))]
    [Migration("20240915123721_AddNewsDbModel")]
    partial class AddNewsDbModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Accesses.DbModels.AccessDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AccessDbModels");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Accesses.DbModels.AccessLogsDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AccessId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TargetAccessId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessId");

                    b.HasIndex("TargetAccessId");

                    b.ToTable("AccessLogsDbModels");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Discord.DbModels.DiscordRoleDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AutomaticRank")
                        .HasColumnType("int");

                    b.Property<ulong>("DiscordRoleId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DiscordRoleDbModels");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Discord.DbModels.DiscordRoleLogsDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AccessId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiscordRoleLogsDbModels");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.News.DbModels.NewsDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("NewsDbModels");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Ranks.DbModels.RightToRankDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Right")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RightToRankDbModels");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Supportfiles.DbModels.SupportfileDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByAccessId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("MinRank")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAccessId");

                    b.ToTable("SupportfileDbModels");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Supportfiles.DbModels.SupportfileEntryDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByAccessId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SupportfileId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAccessId");

                    b.ToTable("SupportfileEntryDbModels");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Supportfiles.DbModels.SupportfileFileUploadDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("EntryId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("SupportfileFileUploadDbModels");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Supportfiles.DbModels.SupportfileLogsDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AccessId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SupportfileId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessId");

                    b.ToTable("SupportfileLogsDbModels");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Accesses.DbModels.AccessLogsDbModel", b =>
                {
                    b.HasOne("ChoiceVFileSystemBlazor.Database.Accesses.DbModels.AccessDbModel", "AccessModel")
                        .WithMany("CreatedAccessLogs")
                        .HasForeignKey("AccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChoiceVFileSystemBlazor.Database.Accesses.DbModels.AccessDbModel", "TargetAccessModel")
                        .WithMany("TargetedAccessLogs")
                        .HasForeignKey("TargetAccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessModel");

                    b.Navigation("TargetAccessModel");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.News.DbModels.NewsDbModel", b =>
                {
                    b.HasOne("ChoiceVFileSystemBlazor.Database.Accesses.DbModels.AccessDbModel", "Creator")
                        .WithMany("NewsDbModels")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Supportfiles.DbModels.SupportfileDbModel", b =>
                {
                    b.HasOne("ChoiceVFileSystemBlazor.Database.Accesses.DbModels.AccessDbModel", "CreatorAccessModel")
                        .WithMany("Supportfiles")
                        .HasForeignKey("CreatedByAccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorAccessModel");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Supportfiles.DbModels.SupportfileEntryDbModel", b =>
                {
                    b.HasOne("ChoiceVFileSystemBlazor.Database.Accesses.DbModels.AccessDbModel", "CreatorAccessModel")
                        .WithMany("SupportfileEntrys")
                        .HasForeignKey("CreatedByAccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorAccessModel");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Supportfiles.DbModels.SupportfileFileUploadDbModel", b =>
                {
                    b.HasOne("ChoiceVFileSystemBlazor.Database.Supportfiles.DbModels.SupportfileEntryDbModel", "EntryModel")
                        .WithMany("FileUploads")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntryModel");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Supportfiles.DbModels.SupportfileLogsDbModel", b =>
                {
                    b.HasOne("ChoiceVFileSystemBlazor.Database.Accesses.DbModels.AccessDbModel", "AccessModel")
                        .WithMany("SupportfileLogs")
                        .HasForeignKey("AccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessModel");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Accesses.DbModels.AccessDbModel", b =>
                {
                    b.Navigation("CreatedAccessLogs");

                    b.Navigation("NewsDbModels");

                    b.Navigation("SupportfileEntrys");

                    b.Navigation("SupportfileLogs");

                    b.Navigation("Supportfiles");

                    b.Navigation("TargetedAccessLogs");
                });

            modelBuilder.Entity("ChoiceVFileSystemBlazor.Database.Supportfiles.DbModels.SupportfileEntryDbModel", b =>
                {
                    b.Navigation("FileUploads");
                });
#pragma warning restore 612, 618
        }
    }
}
